language: node_js
node_js:
  - iojs
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
  # - '5' Disabled due to bug in that version of npm.
  - '4'
  - '3'
  - '2'
  - '1.8'
  - '1.0'
  - '0.12'
  - '0.11'
before_script:
  # Versions of node <10 don't support the latest mocha.
  - node -e 'import(".").catch(() => {});' 2>/dev/null || npm i mocha@~7.1.0
  # Versions of node <8 require even older dependencies.
  - node -e 'const a = {}; const b = {...a};' 2>/dev/null || npm i mocha@~3.5.3 tmp@~0.0.33
stages:
  - coverage
  - test
  - deploy
jobs:
  include:
    - stage: coverage
      node_js: node
      script: npm run coverAndPublish
    - stage: deploy
      if: tag =~ ^[\d\.]+$
      node_js: node
      deploy:
        script: skip
        provider: npm
        email: mtth@apache.org
        api_key:
          secure: ZL5oouERM/Ekv0Gf+ro1mGOcY2T3uQJmp0ZagahlRI/euqB5XnabxCQoAe5MFItZE6BD2Ui5vusQJuuZKNXEMtAjpIazdf9vV0tS/DYrkEniVl1sDBGQuzVaYljUliuMwJbMNzU7z6la6yxE5RgtYjYtqGGrktuQpNDYmJ8GUzE5CjHQsrksAhXgWfLObh913pORYpkKX3JtLiRbrh9kC77RiQRVDPTUVM9uMuwMxO3KI5OjwRQ7OBxlKkFOptEGfyebx9V7opOuRqztYdJLFbfDJQyRi71KF75927HjCgYyD1MTwsyNlaIkkm/e/0TB+b7XNpzOKSPvgfYcObBfNUijoTuTf6waXBoxpwIV79FVMMvNHHnmW7y5HeBypPfwf1CXbRjm+jGC8yREbXA3Tb+W/xojyQsV0xIuFLlFjdr1dasxQhiu8NAaE7OpSnezLewhPH5/ZSVcDNxtpqvYvgo03jaipMmVqqsPEzfVKQ8m0vGjLXYk+6Ek6EO8aNwG2m+extIE4IS3rZYU9OyXhEoYVPJvDE+2RvSpZSKc3xEFnl+UNeilaDWRB52X4FJEEDy7Hgy9dr7rntp+6JAe91OBIc94PdgK9b52UfxkkfmDoo7waAzfAruQFHsGy13L77IcG+kr73ygnAZ2FuHQOD9GeHBlAEOxnsINcEHYf/0=
        on:
          repo: mtth/avsc
          tags: true
